project/frontend/index.html
=> 26 start initial html files

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/ruff-lint.yml, .pre-commit-config.yaml
This reverts commit 550188031371a9273222eaad6aece982bb132248.
=> Revert "Deleted github actions"

tests/README.md
I put together an initial structure of a documentation file for the tests folder based on one of the projects from last year, so that we can maintain consistency across files and sets of tests. my thinking was that after your review, we could share this with the team so that there is more of a structure for their adding their own unit tests to the common folder.
As you've done a lot more QA/GitHub work than I have, I would for sure appreciate any suggestions or additions!!
=> initial version of documentation file for testing framework

static/home_page/index.html
=> Minor update to make user icon consistent. 

static/favorites_page/index.html
=> Minor update to make user icon to circle-user

static/bill_page/bill_page.html, static/css/custom.css
Added in designated color palette to custom.css file. Bill_page.html was committed so James could help me with debugging (it does not have to be merged).
=> 68 configure customcss with color palette

templates/home.html, templates/search.html
Added sign in / sign out logic to home and search page
=> Added sign in / sign out logic to home and search page

apps/core/urls.py, apps/core/utils.py, apps/core/views.py, config/urls.py
The Favorites Page View should be working now, it currently refers to the static favorites.html, so you can temporarily add these lines:
`<hr>
<h2>Favorited Bills SAMPLE</h2>
<ul>
{% for bill in favorited_bills %}
<li>{{ bill.bill_id }} - {{ bill.title }}</li>
{% empty %}
<li>No bills found.</li>
{% endfor %}
</ul>`
to the end of the favorites.html to verify your actual favorited bills while reviewing
=> #111 Favorites View

apps/accounts/urls.py, apps/accounts/views.py, templates/favorites.html
This pull request implements unsubscribe functionality on the currently otherwise static favorites page. If you toggle the alerts button on the favorites page, it will subscribe or unsubscribe you.
To test this:
1. Create a user. Users were recently purged from the users database.
2. Ensure you have read access to the database.
3. Go to http://127.0.0.1:8000/favorites/
4. Hit the toggle button. See if it changes your subscribed status. Hit it again, see if it reverts it to what it was.
5. Review the code
=> 167 create view for unsubscribe toggle on favorites page

apps/core/views.py, templates/search.html
This pull request does the following:
* Updates the data returned by search view to include bill topics
* Renders those topics on the search.html page
I'm not sure how we want to handle topic colors but I just had them match what's on the home page
=> Bill topics added to search view

PRIVACY.md
PR to add privacy policy to dev
=> 177 privacy policy

templates/base.html, templates/bill.html, templates/bill_page.html, templates/favorites.html, templates/home.html, templates/search.html
with this merge, all pages should now force light mode.
=> Hard code all htmls to use light mode

apps/core/views.py, templates/bill_page.html, templates/search.html
I had to make some edits to the views.py to:
1. Change the html that it renders to 
2. Ensure the status date object is in a datetime format so I can pull out month, day, year
=> 76 integrate django templating to bill page

apps/core/urls.py, apps/core/views.py, docs/endpoints/core.md, templates/account/signup.html, templates/privacy_policy.html
This branch does the following:
* Creates a privacy policy page at `/privacy_policy`
* Updates the sign up page to link to the privacy policy page
=> 181 make link to privacy policy on signup

data/updates.py
PR for updating the most_recent_upload table with the date of update
=> adding flag for most recent update

templates/bill_page.html, templates/favorites.html, templates/home.html, templates/search.html
=> make menu button larger across all pages

apps/core/management/commands/populate_notification_queue.py, apps/core/management/commands/send_update_notifications.py, config/settings.py, pyproject.toml, templates/email/notification.html, templates/email/notification.txt
This pull request does the following:
Updates the script to notify users of bill updates to only run if the most recent bill information was uploaded on the same day.
=> 179 write cronjob for notifications

Dockerfile, config/settings.py, docker-compose.yml, templates/bill_page.html, templates/search.html
The site is currently live at
https://billinois.unnamed.computer
I had to make two small changes to get this to work. In the docker-compose I had to set a port that was unique on the class server and also add "build: ." to tell it to use the Dockerfile in the same directory.
Your ALLOWED_HOST setting was hard coded, so I had to make the other adjustment to read it from the env.  You already had a setting there, but I have added the domain name to the .env on the server.  I manually made these changes on the server for now, but can revert that once this is merged.
Right now updating what is running on the server takes a superuser, I'll explore if I can make that something you all can do on your own without sudo.
=> Make required changes for deployment.

apps/core/management/commands/toggle_mock_updates.py, apps/core/management/toggle_mock_updates.py, data/data_reading.py, data/updates.py
So apparently something you can do is simply tell ruff to ignore some lines, I restored your SQL lines!
=> use noqa for ruff to ignore lines

templates/search.html
Karen - my minor attempt to address this bug... feel free to use this branch or ignore it completely as you debug also
=> Fix favorite button bug

templates/search.html
Reformat code to ensure favoriting icon appears again; tried to put "prettier-ignore" comment in a different spot
=> Minor bug fix

Dockerfile, docker-compose.yml
to see if this works in updating on the server
=> update Dockerfile and docker-compose

.github/workflows/pytest.yaml
Create temporary _logs/flat.log during testing workflow
=> Fix pytest

apps/accounts/forms.py
@davidrsteffen Let's see if this change works. I pushed some code adding phone to the custom signup form. Hopefully this fixes it.
=> 244 bug cannot signup on deployed but can on local
